// Export all JSON:API types (re-exported from base)
export type {
  JsonValue,
  Meta,
  LinkObject,
  Link,
  Links,
  PaginationLinks,
  TopLevelLinks,
  TopLevelJsonApi,
  ResourceIdentifier,
  Relationship,
  ToOne,
  ToMany,
  Attributes,
  ResourceObject,
  JsonApiBase,
  ErrorObject,
  ErrorDocument,
  DataDocumentSingle,
  DataDocumentMany,
  JsonApiDocument,
  Paginated,
  Response,
} from '@rachelallyson/planning-center-base-ts';

// Export all People-specific types
export * from './people';

// Re-export commonly used types for convenience
export type {
  AddressAttributes,
  AddressesList,
  AddressResource,
  AddressSingle,
  EmailAttributes,
  EmailResource,
  EmailSingle,
  EmailsList,
  FieldDefinitionAttributes,
  FieldDefinitionResource,
  FieldDefinitionSingle,
  FieldDefinitionsList,
  FieldOptionAttributes,
  FieldOptionResource,
  FieldOptionSingle,
  FieldOptionsList,
  HouseholdAttributes,
  HouseholdResource,
  HouseholdSingle,
  HouseholdsList,
  // Document types
  PeopleList,
  PersonAttributes,
  PersonRelationships,
  PersonResource,
  PersonSingle,
  PhoneNumberAttributes,
  PhoneNumberResource,
  PhoneNumberSingle,
  PhoneNumbersList,
  SocialProfileAttributes,
  SocialProfileResource,
  SocialProfileSingle,
  SocialProfilesList,
} from './people';
